# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gazette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Num\xe9ro')),
                ('pdf', models.FileField(upload_to='svz/gazette/%Y', verbose_name='PDF')),
                ('preview', models.ImageField(upload_to='svz/gazette/p/%Y', verbose_name='Aper\xe7u')),
                ('short_description', models.TextField(verbose_name='Description courte')),
            ],
            options={
                'ordering': ('-number',),
                'verbose_name': 'Gazette',
                'verbose_name_plural': 'Gazettes',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('sciper', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='SCIPER')),
                ('name', models.TextField(max_length=200, verbose_name='Nom')),
                ('contaminations', models.IntegerField(default=0, verbose_name='Contaminations')),
                ('token_spent', models.IntegerField(default=0, verbose_name='Token d\xe9pens\xe9s')),
                ('zombie', models.BooleanField(default=False, verbose_name='Zombie ?')),
                ('email', models.EmailField(max_length=300, null=True, verbose_name='Email')),
            ],
            options={
                'ordering': ('contaminations',),
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
            options={
                'ordering': ('sponsor', 'name'),
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('text', models.TextField(max_length=500, verbose_name='Contenu')),
                ('icon', models.CharField(choices=[('fa-lock', 'Cadenas'), ('fa-cog', 'Rouage'), ('fa-user', 'Personne'), ('fa-male', 'Homme'), ('fa-female', 'Femme'), ('fa-server', 'Serveur'), ('fa-crosshair', 'Viseur'), ('fa-check', 'Check'), ('fa-ticket', 'Ticket'), ('fa-heartbeat', 'Coeur'), ('fa-medkit', 'Medkit'), ('fa-trophy', 'Troph\xe9')], max_length=20, verbose_name='Icone')),
                ('importance', models.IntegerField(choices=[(0, 'Extr\xeame'), (1, 'Haute'), (2, 'Moyenne'), (3, 'Faible')], default=1, verbose_name='Importance')),
            ],
            options={
                'ordering': ('importance',),
                'verbose_name': 'R\xe8gle',
                'verbose_name_plural': 'R\xe8gles',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nouveau sponsor', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(default='Aucune description', verbose_name='Description')),
                ('grade', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], verbose_name='Grade')),
                ('logo', models.ImageField(height_field='logo_height', upload_to='svz/sponsors/%Y', width_field='logo_width')),
                ('logo_width', models.IntegerField(default=125, verbose_name='Largeur')),
                ('logo_height', models.IntegerField(default=125, verbose_name='Hauteur')),
                ('url', models.URLField(verbose_name='Lien externe')),
            ],
            options={
                'ordering': ('-grade',),
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.AddField(
            model_name='reward',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svz.Sponsor', verbose_name='Sponsor'),
        ),
    ]
