# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciper', models.IntegerField(default=0, unique=True)),
                ('name', models.TextField(max_length=200)),
                ('contaminations', models.IntegerField(default=0)),
                ('token_spent', models.IntegerField(default=0)),
                ('zombie', models.BooleanField(default=False)),
                ('revive_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('contaminations',),
            },
        ),
    ]
