# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sciper',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
