# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0003_auto_20170209_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svz',
            options={'verbose_name': 'D\xe9tails SvZ'},
        ),
        migrations.AlterField(
            model_name='svz',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='svz',
            name='events',
            field=models.CharField(default='Entrez un descriptif des \xe9v\xe8nements', max_length=500),
        ),
        migrations.AlterField(
            model_name='svz',
            name='inscription',
            field=models.CharField(default='Entrez les d\xe9tails', max_length=5000),
        ),
        migrations.AlterField(
            model_name='svz',
            name='pres_vid',
            field=models.URLField(default="Entrez l'url youtube de la vid\xe9o de pr\xe9sentation", verbose_name='Vid\xe9o de pr\xe9sentation Youtube'),
        ),
        migrations.AlterField(
            model_name='svz',
            name='rules_vid',
            field=models.URLField(default="Entrez l'url youtube de la vid\xe9o des r\xe8gles", verbose_name='Vid\xe9o de r\xe8gles Youtube'),
        ),
        migrations.AlterField(
            model_name='svz',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de d\xe9but'),
        ),
    ]
