# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0003_auto_20160322_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gazette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Num\xe9ro')),
                ('pdf', models.FileField(upload_to='svz/gazette/%Y', verbose_name='PDF')),
                ('preview', models.ImageField(upload_to='svz/gazette/p/%Y', verbose_name='Aper\xe7u')),
            ],
            options={
                'ordering': ('number',),
                'verbose_name': 'Gazette',
                'verbose_name_plural': 'Gazettes',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nouveau sponsor', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(default='Aucune description', verbose_name='Description')),
                ('grade', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], verbose_name='Grade')),
                ('logo', models.ImageField(height_field='logo_height', upload_to='svz/sponsors/%Y', width_field='logo_width')),
                ('logo_width', models.IntegerField(default=125, verbose_name='Largeur')),
                ('logo_height', models.IntegerField(default=125, verbose_name='Hauteur')),
            ],
            options={
                'ordering': ('-grade',),
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
