# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0004_auto_20170209_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svz',
            name='pres_vid',
            field=models.TextField(default="Entrez l'url youtube de la vid\xe9o de pr\xe9sentation", verbose_name='Vid\xe9o de pr\xe9sentation Youtube'),
        ),
        migrations.AlterField(
            model_name='svz',
            name='rules_vid',
            field=models.TextField(default="Entrez l'url youtube de la vid\xe9o des r\xe8gles", verbose_name='Vid\xe9o de r\xe8gles Youtube'),
        ),
    ]
