# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0005_sponsor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gazette',
            name='short_description',
            field=models.TextField(default='Nothing', verbose_name='Description courte'),
            preserve_default=False,
        ),
    ]
