# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0005_auto_20170209_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svz',
            options={'verbose_name': 'D\xe9tails SvZ', 'verbose_name_plural': 'D\xe9tails SvZ'},
        ),
        migrations.AlterField(
            model_name='svz',
            name='events',
            field=models.TextField(default='Entrez un descriptif des \xe9v\xe8nements', max_length=500),
        ),
        migrations.AlterField(
            model_name='svz',
            name='inscription',
            field=models.TextField(default='Entrez les d\xe9tails', max_length=5000),
        ),
        migrations.AlterField(
            model_name='svz',
            name='place',
            field=models.TextField(default='Entrez le lieu', max_length=200),
        ),
        migrations.AlterField(
            model_name='svz',
            name='pres_vid',
            field=models.CharField(default="Entrez l'url youtube de la vid\xe9o de pr\xe9sentation", max_length=50, verbose_name='Vid\xe9o de pr\xe9sentation Youtube'),
        ),
        migrations.AlterField(
            model_name='svz',
            name='rules_vid',
            field=models.CharField(default="Entrez l'url youtube de la vid\xe9o des r\xe8gles", max_length=50, verbose_name='Vid\xe9o de r\xe8gles Youtube'),
        ),
    ]
