# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0006_gazette_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svz.Sponsor', verbose_name='Sponsor')),
            ],
            options={
                'ordering': ('sponsor', 'name'),
                'verbose_name': 'Lots',
            },
        ),
    ]
