# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0006_auto_20170224_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='faction',
            field=models.BooleanField(default=False, verbose_name='Troisi\xe8me faction?'),
        ),
    ]
