# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svz', '0007_player_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='classe',
            field=models.CharField(max_length=100, null=True, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='player',
            name='weapon',
            field=models.CharField(max_length=100, null=True, verbose_name='Arme'),
        ),
    ]
