# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Pr\xe9nom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('post', models.CharField(max_length=100, verbose_name='Poste')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('email', models.EmailField(max_length=254, verbose_name='Addresse de contact')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Membre du comit\xe9',
                'verbose_name_plural': 'Membres du comit\xe9',
            },
        ),
        migrations.CreateModel(
            name='MainPageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('order', models.IntegerField(verbose_name='Position')),
            ],
            options={
                'ordering': ('order', '-pk'),
                'verbose_name': "Section page d'acceuil",
                'verbose_name_plural': "Sections page d'accueil",
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Nouvelle news', max_length=200, verbose_name='Titre')),
                ('content', models.TextField(max_length=10000, verbose_name='Contenu')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
