# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('semesters', models.IntegerField(choices=[(2, 'Annuelle'), (1, 'Semestrielle')], verbose_name='Dur\xe9e')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes',
            },
        ),
    ]
